version: '3'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234

  server:
    build: TaskManager/
    restart: always
    ports:
      - 80:8080
  
    depends_on:
      - database
      
    command: ["dotnet", "ef", "database update"]
    