version: '3'
services:
  database:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: database
    volumes:
      - db_volume:/var/lib/postgresql/data/

  server:
    image: artemilin15474/to-do-list:latest
    build: ./TaskManager/
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 80:8080

volumes:
  db_volume:
