version: "3.8"

x-logging: &logging
    logging:
      driver: "loki"
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-batch-size: "100"
        loki-retries: 2
        loki-max-backoff: 1000ms
        loki-timeout: 1s

services:
  database:
    <<: *logging
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: database
    volumes:
      - db_volume:/var/lib/postgresql/data/

  server:
    <<: *logging
    image: artemilin15474/to-do-list:latest
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - net
      - default
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 512M


volumes:
  db_volume:

networks:
  net:
    external: true
    name: nginx_net
