version: '3'

networks:
  net:
    driver: bridge

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: database
    volumes:
      - db_volume:/var/lib/postgresql/data/
    networks:
      - net
    ports:
      - 5432

  server:
    image: artemilin15474/to-do-list:v4
    build: TaskManager/
    restart: always
    depends_on:
      - database

    networks:
      - net
    ports:
      - 80:8080

volumes:
  db_volume: