version: "3.8"

x-logging: &logging
    logging:
      driver: "loki"
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-batch-size: "100"
        loki-retries: 2
        loki-max-backoff: 1000ms
        loki-timeout: 1s


services:
  database:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: database
    volumes:
      - db_volume:/var/lib/postgresql/data/
    <<: *logging

  server:
    image: artemilin15474/to-do-list:latest
    build: ./TaskManager/
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 80:8080
    <<: *logging

volumes:
  db_volume:
