version: "3.9"

services:
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_storage:/prometheus
    depends_on:
      - cadvisor
    networks:
      - net
      - default
    deploy:
      resources:
        limits:
          memory: 256M

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - net
      - default
    deploy:
      resources:
        limits:
          cpus: 0.05
          memory: 128M

  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
      - loki
    networks:
      - net
      - default
    deploy:
      resources:
        limits:
          memory: 256M

  loki:
    image: grafana/loki
    restart: unless-stopped
    environment:
      - TZ="Europe/Moscow"
    volumes:
      - ./loki/retention-config.yaml:/etc/loki/retention-config.yaml
    command: -config.file=/etc/loki/retention-config.yaml -config.expand-env=true
    ports:
      - 3100:3100
    networks:
      - net
      - default
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: 256M

volumes:
  grafana_storage:
  prometheus_storage:

networks:
  net:
    external: true
    name: nginx_net
