version: "3.8"

x-logging: &logging
    logging:
      driver: "loki"
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-batch-size: "100"
        loki-retries: 2
        loki-max-backoff: 1000ms
        loki-timeout: 1s

services:
  nginx:
    <<: *logging
    image: nginx
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/cloudflare.crt:/etc/nginx/ssl/cert/cloudflare.crt:ro
      - ./ssl/cloudflare.key:/etc/nginx/ssl/private/cloudflare.key:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - default
      - net

networks:
  net: