name: Docker Image CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login into docker regestry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push image to docker hub
        uses: docker/build-push-action@v5
        with:
          context: ./TaskManager/
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/to-do-list:latest

  deploy:
    runs-on: ubuntu-latest
    needs: publish-image
    
    steps:
      - name: Connect to VPS and restart docker containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: |
            cd ${{ secrets.PATH_TO_WORK_DIR }};
            git checkout master;
            git pull;
            docker-compose down;
            docker system prune --all --force;
            docker-compose up -d;
            
        
